
CREATE TABLE products
(
  id          INT AUTO_INCREMENT
    PRIMARY KEY,
  category    VARCHAR(128) NOT NULL,
  title       VARCHAR(128) NOT NULL,
  description VARCHAR(255) NOT NULL,
  price       INT          NOT NULL,
  options     VARCHAR(255) NOT NULL,
  `image-min` VARCHAR(127) NOT NULL,
  `image-max` VARCHAR(127) NOT NULL
);




INSERT INTO CourseProject.products (id, category, title, description, price, options, image_min, image_max) VALUES (1, 'men collection', 'Mango People T-shirt', 'Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.', 52, '{"material":"cotton","designer":"binburhan","color":["red","green","white"],"size":["L","XL","XXL"]}', 'product-men-4.jpg', 'product-men-4.jpg');
INSERT INTO CourseProject.products (id, category, title, description, price, options, image_min, image_max) VALUES (2, 'men collection', 'Mango People T-shirt', 'Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.', 52, '{"material":"cotton","designer":"binburhan","color":["red","green","white"],"size":["L","XL","XXL"]}', 'product-men-1.jpg', 'product-men-1.jpg');
INSERT INTO CourseProject.products (id, category, title, description, price, options, image_min, image_max) VALUES (3, 'men collection', 'Mango People T-shirt', 'Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.', 52, '{"material":"cotton","designer":"binburhan","color":["red","green","white"],"size":["L","XL","XXL"]}', 'product-men-2.jpg', 'product-men-2.jpg');
INSERT INTO CourseProject.products (id, category, title, description, price, options, image_min, image_max) VALUES (4, 'men collection', 'Mango People T-shirt', 'Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.', 52, '{"material":"cotton","designer":"binburhan","color":["red","green","white"],"size":["L","XL","XXL"]}', 'product-men-3.jpg', 'product-men-3.jpg');
INSERT INTO CourseProject.products (id, category, title, description, price, options, image_min, image_max) VALUES (5, 'men collection', 'Mango People T-shirt', 'Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.', 52, '{"material":"cotton","designer":"binburhan","color":["red","green","white"],"size":["L","XL","XXL"]}', 'product-men-5.jpg', 'product-men-5.jpg');
INSERT INTO CourseProject.products (id, category, title, description, price, options, image_min, image_max) VALUES (6, 'men collection', 'Mango People T-shirt', 'Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.', 52, '{"material":"cotton","designer":"binburhan","color":["red","green","white"],"size":["L","XL","XXL"]}', 'product-men-6.jpg', 'product-men-6.jpg');
INSERT INTO CourseProject.products (id, category, title, description, price, options, image_min, image_max) VALUES (7, 'men collection', 'Mango People T-shirt', 'Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.', 52, '{"material":"cotton","designer":"binburhan","color":["red","green","white"],"size":["L","XL","XXL"]}', 'product-men-7.jpg', 'product-men-7.jpg');
INSERT INTO CourseProject.products (id, category, title, description, price, options, image_min, image_max) VALUES (8, 'men collection', 'Mango People T-shirt', 'Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.', 52, '{"material":"cotton","designer":"binburhan","color":["red","green","white"],"size":["L","XL","XXL"]}', 'product-men-8.jpg', 'product-men-8.jpg');
INSERT INTO CourseProject.products (id, category, title, description, price, options, image_min, image_max) VALUES (9, 'men collection', 'Mango People T-shirt', 'Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.', 52, '{"material":"cotton","designer":"binburhan","color":["red","green","white"],"size":["L","XL","XXL"]}', 'product-men-9.jpg', 'product-men-9.jpg');
